package.json
=> package.json setup

.gitignore, index.html, main.js, package.json
Initialized the new Electron application and added .gitignore file.
No testing methods have been written. Application can be ran with npm start.
=> Initalized electron application and added gitIgnore file

.gitignore
Finally fixed gitIgnore issue
N/A
=> Finally worked

data/users.json, service/login.js
- Connected dashboard on successful login
- Stored UserName to locaStorage
Manually Tested
=> Connected dashboard and added UserName on login to localstorage

service/searchAllSongs.js
Search for song in the music.json file. Stores top five results in an array.
-
Hard coded the input, displayed output using console. 
Make sure to change the file path to read the music.json file.
=> This is the search script

main.js, service/dashboard.js, service/playlist.js, styles/dashboard.css, styles/playlist.css, view/dashboard.html, view/playlist.html
Completed UI for dashboard.  Users can now search individual songs by title, artist, or release.  Songs are then displayed to the User.  The user can then click "Play Song" to play the chosen song.  Routes have been set up with the relevant Json files with the dashboard.js service file.  A playlist view has been created.
Waiting now on playlist and user data to be added to complete final set up.
Release Search will be changed to Playlist Search and then songs within a playlist will be displayed and chosen to play...
- [x ] New feature (non-breaking change which adds functionality)
Tested each search with
Song: La Culpa
Artist: Andy Andy
Then press play song button
Listen to song...
Waiting on playlist.json and user.json data
=> Dashboard backend setup playlist frontend backend setup

service/dashboard.js, service/searchAllSongs.js, view/dashboard.html
Used searchAllSongs JS in Dashboard UI
Integrated Angels search function with dashboard.js functions to work on dashboard HTML...
Leaving the dashboard.js for extra functions regarding displaying playlists
- [x ] New feature (non-breaking change which adds functionality)
Used La Culpa and Andy Andy as search criteria
=> Finished combining the code

service/playlist_frontend.js
Made it so that a playlist plays each song one after another when the audio is completely done. If the playlist index reaches the last song in the playlist, it will return to the first song on the playlist.
Tested using these search results:
As Nice As Can Be Eagles Of Death Metal
As the Hog Pisseth All Leather
Nothin' On You [feat. Bruno Mars]
N/A
=> fixed playSongs to play next song

Client/service/registration.js, Server/responseObjectRef.json
Created a JSON reference object file
N/A
=> Created server response file

Server/LoginServices.java, Server/Songs.java
function now returns JSON object that matches the JSON objects located in playlist.json file.  Front end will now have user playlist data and user name login info once user has logged in.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Updated return type for login function

Server/RegisterServices.java, Server/RegisterServicesTest.java
Made it so registration method creates a jsonobject which has the response message which is then stringified and returned to caller
Updated test class to reflect these changes
=> Changed registration to have json response

Server/UserPlaylists.java
Added Gson to create JSON objects to be used for UserPlaylists to later be sent to dashboard from Login Services 
- [ x] New feature (non-breaking change which adds functionality)
=> Hook up JSON objects to class

Server/PlaylistServices.java, Server/RegisterServices.java
All methods expected to return form of communication now return a stringified JSON based on if it was able to perform that request successfully or not
N/A
=> Updated PlaylistServices to return stringified JSON

Server/SongServices.java
Created song services to get a chunk of a song from a song ID and the fragment location
=> Song services

Server/Artist.java, Server/Release.java, Server/Song.java, Server/Songs.java
=> Classes for song json

Client/data/objectReference1.json, Client/main.js, Client/service/login.js, Client/service/registration.js, Server/SocketLayer.java
=> Changes to dispatcher

Server/.classpath, Server/.gitignore
=> Updating gitignore

Server/Dispatcher.java
Load up the json response without any backlash 
A simple login request and response 
=> Dipatcher added

.classpath, .project, Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java, Server/src/dfs/RemoteInputFileStream.java
1. create metadata file structure
2.append to the chord and updates metadata
class demo
=> File create append method complete

Server/src/dfs/Chord.java, Server/src/dfs/ChordMessageInterface.java, Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java, Server/src/dfs/RemoteInputFileStream.java
Finished read command in DFS and updated the DFSCommandLine to parse read command input
Created test chords and attempted to read json files (users.json, playlists.json, etc)
=> Finished read command

Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java
created the head and tail command to read both the head of the file stream and the tail
=> head and tail command

Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java
Delete all the physical files of pages and JSONFile from MetaData
=> Logical File Deletion

Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java, Server/src/dfs/RemoteInputFileStream.java
Fixed package errors, exception error, and a missing curly brace on the delete method
=> Fixed dependency exception errors

Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java
=> List file branch

Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java
=> Finished move method

Server/src/clientComm/Main.java, Server/src/dfs/DFS.java, Server/src/dfs/RemoteInputFileStream.java, Server/src/services/pathHolder.java
-Added a Read Method which returns a file's content created on a dfs object of port 1234 as a string
DFS object is static so that it only joins once
=> Added Read method and DFS connection in pathHolder

Server/src/dfs/DFS.java
=> fixed problem to remove file from meta data

Server/src/dfs/DFS.java
Added read from metadata on dfs commands
=> Added write and read to metadata on all commands

Server/src/gson/Users.java, Server/src/services/LoginServices.java, Server/src/services/RegisterServices.java, Server/src/services/SearchServices.java
Integrated DFS with services by geting JSON objects from JSON string and adding them into the List of User objects using a parser
=> Integrated DFS with services

Server/src/services/RegisterServices.java
Updated getUserPlaylists inside RegisterServices to read from dfs instead of the actual playlist file
N/A
=> Update getUserPlaylists to read from dfs

Server/src/services/pathHolder.java
Added pathholder write method
Tested method in pathholder
=> Added write method for jsonString to dfs

Server/src/services/RegisterServices.java
=> Updated registerServices to work with DFS writeFile

Server/src/dfs/DFS.java, Server/src/services/RegisterServices.java, Server/src/services/pathHolder.java
Registration Connected and removed syso statements
bug[]
Manually Tested
=> Registration Connected

Server/src/clientComm/Main.java, Server/src/services/LoginServices.java, Server/src/services/RegisterServices.java, Server/src/services/SearchServices.java, Server/src/services/pathHolder.java
Automated dfs initalization
Manually Tested
=> Automated startup for dfs

Server/src/dfs/RemoteInputFileStream.java
Newest remoteinputfile
Manually
=> Replaced Input file stream with new version

Server/src/clientComm/Main.java, Server/src/dfs/RemoteInputFileStream.java, Server/src/services/PlaylistServices.java, Server/src/services/SearchServices.java, Server/src/services/pathHolder.java
Fixed playlist services
Added misc functionalities
Manually
=> Revisions of new code, fixed playlistservices

Server/src/clientComm/Main.java, Server/src/gson/UserPlaylists.java, Server/src/services/PlaylistServices.java, Server/src/testplaylists.json
Playlist services working
Manually tested
Let commented code in case things break
=> Playlist service dfs update

Server/.gitignore, Server/src/dfs/Chord.java, Server/src/dfs/ChordMessageInterface.java, Server/src/dfs/DFS.java, Server/src/dfs/MapReduceInterface.java, Server/src/dfs/Mapper.java
- [x ] New feature (non-breaking change which adds functionality)
=> Map reduce implementation

Server/src/dfs/Chord.java, Server/src/dfs/ChordMessageInterface.java, Server/src/dfs/DFS.java, Server/src/dfs/Mapper.java
Added helper function to append an empty page.
Added TODO stubs marking methods that need to be implemented
Removed current errors in project
N/A
=> Fixed implementation errors, added TODO stubs

Server/src/dfs/Chord.java, Server/src/dfs/ChordMessageInterface.java, Server/src/dfs/DFS.java
Fixed some errors the professor pointed out
=> Fixed errors the professor pointed out

Server/src/dfs/Chord.java
Reads meta data from page and parses it into an array of json objects and adds each json object to the mapper.map function. marks page completed on coordinator
=> map context

Server/15441370327994453/repository/8555781317612585347, Server/src/dfs/Chord.java, Server/src/dfs/ChordMessageInterface.java, Server/src/dfs/DFS.java, Server/src/dfs/DFSCommand.java, Server/src/dfs/FileMapObject.java, Server/src/dfs/MapReduceInterface.java, Server/src/dfs/Mapper.java, Server/src/gson/PrimativeHolder.java
Fixed all bugs up to the Mapper map method
Added an easy way to test mapreduce off of dfsCommand
Manually Tested
-For testing, run DFS command enter port, when prompted to test mapreduce enter "y" or "yes"
=> Fixing stuff up to map method

Server/src/dfs/DFS.java, Server/src/dfs/Mapper.java, Server/src/services/SearchServices.java, Server/src/services/pathHolder.java
=> Fixed small error

Server/src/dfs/DFS.java, Server/src/dfs/Mapper.java
=> Fixed formatting issue of appended jsonString
